name: Go package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: commit
        uses: pr-mpt/actions-commit-hash@v2
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.15

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -json ./... > TestResults-${{ steps.commit.outputs.short }}.json

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: Go-results-${{ steps.commit.outputs.short }}
          path: TestResults-${{ steps.commit.outputs.short }}.json
